############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Apartment"
url = "/apartment"
weight = 2

[[main]]
name = "Amenities"
url = "/amenities"
weight = 3

[[main]]
name = "Location"
url = "/location"
weight = 4

[[main]]
name = "Booking"
url = "/booking"
weight = 5

[[main]]
name = "Contact"
url = "/contact/"
weight = 6

# footer menu
[[footer]]
name = "Legal Notice"
url = "/pages/legal-notice"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/pages/privacy-policy"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "/pages/terms-conditions"
weight = 3

[[footer]]
name = "Contact"
url = "/contact/"
weight = 4
